export const DETAIL_CHECKBOX = {
  demo: 'demo',
  charA: 'A',
  charB: 'B',
  charC: 'C',
  charD: 'D',
  employeeCheckbox: 'พนักงาน',
  farmerCheckbox: 'เกษตรกรชาวสวนยาง',
  generalCheckbox: 'ผู้ใช้งานทั่วไป',
  businessOperatorCheckbox: 'ผู้ประกอบกิจการยาง',
  developmentGroupCheckbox: 'กลุ่มพัฒนาสวนยาง',
  farmersInstituteCheckbox: 'สถาบันเกษตรกรชาวสวนยาง',
  introductoinPagePermission: 'การจัดการ Introduction Page',
  sustainabilityFarmerPermission: 'การจัดการเกษตรกรชาวสวนยางต้นแบบ',
  linkGoogleFormPermission: 'การจัดการแบบสอบถาม',
  budgetPlanTrackingPermission: 'การติดตามการดำเนินงานและผลการใช้จ่ายงบประมาณ',
  budgetSumPermission: 'สรุปแผนและผลงบประมาณ',
  budgetProjectPermission: 'โครงการที่ได้รับการจัดสรร/การลงนามสัญญา',
  assetFullViewPermission: 'เรียกดูโครงการงบลงทุนทั้งหมด สำหรับ ฝ่ายบริหารทรัพย์สิน',
  strategyFullViewPermission: 'เรียกดูโครงการงบทำการทั้งหมด สำหรับ ฝ่ายยุทธศาสตร์',
  budgetProjectIsContractCheckbox: 'มีคู่สัญญา',
  budgetProjectNonContractCheckbox: 'ไม่มีคู่สัญญา',
  checkAll: 'เลือกทั้งหมด',
  onGoingProject: 'โครงการต่อเนื่อง'
};
